language: node_js
node_js:
  - 'node'

notifications:
  slack: myaegee:Qe6muWYLbq3K6zt1VcLVx9br

services:
  - postgresql
  - docker

env:
  - NODE_ENV=test

addons:
  postgresql: "9.6"

before_install:
  - npm install

install:
  - cp ./config/index.js.example ./config/index.js

script:
  - npm run lint
  - npm audit
  - npm test
  - codecov

# after_script:
#   - sudo docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
#   - sudo docker tag aegee/oms-events aegee/oms-events:${TRAVIS_COMMIT}
#   - sudo docker push aegee/oms-events:${TRAVIS_COMMIT}
#   - sudo docker tag aegee/oms-events:${TRAVIS_COMMIT} aegee/oms-events:latest
#   - sudo docker push aegee/oms-events:latest
#   #if: tag
