language: node_js
node_js:
  - 'node'

notifications:
  slack: myaegee:Qe6muWYLbq3K6zt1VcLVx9br

services:
  - mongodb

before_install:
  - npm install

install:
  - cp ./lib/config/configFile.json.example ./lib/config/configFile.json