version: "3.4"
### OMS EVENTS   #######################################
services:
    postgres-oms-events:
        restart: always
        image: postgres:10
        volumes:
            - postgres-oms-events:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "${PW_POSTGRES}"

    oms-events:
        restart: on-failure
        image: aegee/oms-events:latest
        volumes:
            - oms-events-media:/usr/app/media
            - shared:/usr/app/shared:ro
        depends_on:
            - postgres-oms-events
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: "${BUGSNAG_KEY_EVENTS}"
            PG_PASSWORD: "${PW_POSTGRES}"
            NODE_ENV: "${MYAEGEE_ENV}"
            HOST: "${SUBDOMAIN_FRONTEND}${BASE_URL}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8084/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # cpu_count: 1
        # mem_limit: 900m
        labels:
            - "traefik.backend=oms-events"
            - "traefik.port=8084"
            - "traefik.frontend.rule=PathPrefix:/services/oms-events/api;PathPrefixStrip:/services/oms-events/api"
            - "traefik.frontend.priority=110"
            - "traefik.enable=true"

    oms-events-static:
        restart: on-failure
        image: aegee/nginx-static:latest
        volumes:
            - oms-events-media:/usr/app/media:ro
            - ./${PATH_OMS_EVENTS}/oms-events-static/status.json:/usr/app/status.json:ro
            - ./${PATH_OMS_EVENTS}/oms-events-static/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./${PATH_OMS_EVENTS}/oms-events-static/sites/default:/etc/nginx/sites-available/default:ro
            - shared:/usr/app/shared:ro
        expose:
            - "80"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        labels:
            - "traefik.backend=oms-events-static"
            - "traefik.port=80"
            - "traefik.frontend.rule=PathPrefix:/media/events;PathPrefixStrip:/media/events"
            - "traefik.frontend.priority=110"
            - "traefik.enable=true"

volumes:
    postgres-oms-events:
        driver: local
    oms-events-media:
        driver: local
    shared:
        driver: local

networks:
    default:
        external:
            name: OMS
