version: '3.2'
### OMS STATUTORY     #######################################
### mongodb Container #######################################
services:
    postgres-oms-events:
        restart: always
        image: postgres:10
        volumes:
            - postgres-events:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${PW_POSTGRES}

    oms-events:
        restart: on-failure
        build:
            context: ./$PATH_OMS_EVENTS/..
            dockerfile: ./docker/oms-events/Dockerfile.dev
        image: aegee/oms-events:dev
        volumes:
            - oms-events-media:/usr/app/media
            - ./$PATH_OMS_EVENTS/../:/usr/app/src
            - shared:/usr/app/shared:ro
        links:
            - postgres-oms-events
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: 6f6a7c00507fceca0818c48405dbd2a6
            PG_PASSWORD: ${PW_POSTGRES}
        labels:
            - "traefik.backend=oms-events"
            - "traefik.port=8084"
            - "traefik.frontend.rule=PathPrefix:/services/oms-events/api;PathPrefixStrip:/services/oms-events/api"
            - "traefik.frontend.priority=110"
            - "traefik.enable=true"

volumes:
    postgres-events:
        driver: "local"
    oms-events-media:
        driver: "local"
    shared:
        driver: "local"
